// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6NPwGQA9Ji5p34u59i5jDU0N6A4Mjz48',
    appId: '1:767964477514:web:80496ba64e029c39f2ceb3',
    messagingSenderId: '767964477514',
    projectId: 'mealbridge-2025',
    authDomain: 'mealbridge-2025.firebaseapp.com',
    storageBucket: 'mealbridge-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2XfK66-XnmGsz_dr0W1Ex7hZCrGKYsPM',
    appId: '1:767964477514:android:8fa964d72b967d59f2ceb3',
    messagingSenderId: '767964477514',
    projectId: 'mealbridge-2025',
    storageBucket: 'mealbridge-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD52xvTFg1diGW6unaypdqKkUiX_3tmnNQ',
    appId: '1:767964477514:ios:047a99dacd7ec6c3f2ceb3',
    messagingSenderId: '767964477514',
    projectId: 'mealbridge-2025',
    storageBucket: 'mealbridge-2025.firebasestorage.app',
    iosBundleId: 'com.example.mealbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD52xvTFg1diGW6unaypdqKkUiX_3tmnNQ',
    appId: '1:767964477514:ios:047a99dacd7ec6c3f2ceb3',
    messagingSenderId: '767964477514',
    projectId: 'mealbridge-2025',
    storageBucket: 'mealbridge-2025.firebasestorage.app',
    iosBundleId: 'com.example.mealbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6NPwGQA9Ji5p34u59i5jDU0N6A4Mjz48',
    appId: '1:767964477514:web:ef564fce17bc8865f2ceb3',
    messagingSenderId: '767964477514',
    projectId: 'mealbridge-2025',
    authDomain: 'mealbridge-2025.firebaseapp.com',
    storageBucket: 'mealbridge-2025.firebasestorage.app',
  );
}
